---
- hosts: os

  tasks:
  - name: Copy selfcerts.tar.gz
    copy: src=../roles/host-init/files/selfcerts.tar.gz dest=/tmp/
    sudo : yes

  - name: extract tar
    shell: tar -zxvf /tmp/selfcerts.tar.gz -C /tmp
    sudo: yes

  - name: deploy ca to trust
    shell: cp /tmp/selfcerts/ca.crt /etc/pki/ca-trust/source/anchors/registry.ssecloud.com.crt
    sudo: yes

  - name: update-ca-trust
    shell: update-ca-trust
    sudo: yes

  - name: deploy self-ca
    shell: tar -zxvf /tmp/selfcerts/certs.tar.gz -C /etc/docker/
    sudo: yes

  - name: stop docker
    shell: service docker stop
    sudo: yes

  - name: start docker
    shell: service docker start
    sudo: yes
