---
- hosts: os
  vars:
    user: test
    password: "$6$rounds=100000$O2BHfT2XIF6oDb9w$8Hhv4vOrLN6JF/nRVYDd8zZdnn9TNkQutyYYywIcPF2kRiHgkwAjqHIN7sDUkd1DcjLRABWT9ULHZPBOF2bZS/"
  remote_user: root
  tasks:
  - name: Add user {{ user }}
    user: name={{user}} comment="dataman user" password={{ password }}

  - name: Config /etc/sudoers
    lineinfile: dest=/etc/sudoers state=present  line='{{item}}' validate='visudo -cf %s'
    with_items:
           - "{{ user }} ALL=(ALL) /bin/sh, /bin/bash, /bin/curl, /usr/bin/curl, /bin/yum, /usr/bin/yum, /bin/rpm, /usr/bin/rpm"
           - "Defaults: {{user}}  !requiretty"
